### PR TITLE
Fixed #80 by hard-coding around magic number confict in recusive delays.

### PR DESCRIPTION
**Pull request by burnsauce**

### CODE REVIEW

**Comment by samdoshi** [comment]
Looks solid to me. I'll give it a day or 2 for any one else to comment, then merge.

**Comment by burnsauce** [comment]
I didn't realize that further commits to my fork would attach themselves to this pull request.

Looks like a generated op_enum.h is needed for your travis-ci checks.  Can it be updated to run the generator as per the new Makefile, or do we need a copy included no matter what?

**Comment by samdoshi** [comment]
No worries. I haven't got time to go through fixing this with you today. It might have to wait till later on this week.

Anyway, short summary / info dump....

Firstly, I've just noticed that this PR is against my personal fork `samdoshi/teletype`, rather than the upstream `monome/teletype`, looks like you've clicked the fork button on my repo, rather than upstream. You can fix this by deleting your repo on GitHub and re-forking... a bit extreme unfortunately.

Branches...: `git` generally encourages you to place each feature on it's own branch, and GitHub more strongly enforces this by tying each PR to a branch. Two ways to fix this... delete it all and do them again, or use `git cherry-pick` to create the new branches. Make sure that each feature branch is cleanly built on top of the `monome/teletype` `master` branch.

In general try to never write code on the `master` branch when working collaboratively with `git`, it just causes headaches.

Once you've got each feature on it's own branch, open up some new PRs against `monome/teletype`.

You probably also want to add some remotes to your repo so you can sync with upstream:

https://help.github.com/articles/syncing-a-fork/

----

A few other notes. Not sure about the `op_enums` stuff, need to think about it. Get it in the habit of running the tests and building the simulator before committing to catch these bugs ahead of time.

You don't need to add your own private ignores to `.gitignore`, you can ignore them in your own local clone:

https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-somes-files-locally

---

Sorry for the stream of consciousness of it. I'm just a bit busy for a few days. But if there are specific things that are stopping you from getting stuff done let me know.

(And thank you! All this is really appreciated.)

**Comment by burnsauce** [comment]
No problem.  I'll get to work on my git skills tomorrow.

Thank you for your guidance.  This is my first real collaborative project
so _your_ help is greatly appreciated. :-)

P.S.: looks like a few of the open issues in the tracker have already been
patched in teletype master.

**Comment by samdoshi** [comment]
> P.S.: looks like a few of the open issues in the tracker have already been
patched in teletype master.

Bump the tickets and I can close them

**Comment by scanner-darkly** [comment]
re: `op_enums` - one thing to consider is that having it included would mean that people that are not interested in touching ops don't have to install ragel.

**Comment by burnsauce** [comment]
That's true, but it prevents us from integrating config macros to disable
or enable support for certain operators.

I'd like to be able to disable all I2C support at compile time, for
instance (e.g.: #define CONFIG_NO_I2C).  My build would have no need for
any I2C-related operator, so they could be cut out.  I don't think a ragel
installation is too much to ask of someone building from source TBH,
especially in light of the docs requirements!  Just my 2 cents.

(Alternately, who would be able to follow all of the directions required to
get a build running but have some sort of issue with installing ragel?)

Does the CI process support ragel, anyway?

-----

As I'm sure you've seen, I've pushed the first two bugfix commits.  If it
looks like I'm doing things correctly, I'll go ahead and prepare branches
for the MSPB operator and the tracker data entry improvement.

**Comment by scanner-darkly** [comment]
how having `op_enums` checked in prevents you from having your own custom build? if you are adding your own `define`s you wouldn't want that checked in into the main branch anyway. and if you are working off your own branch you can add your own custom git ignores, as @samdoshi mentioned.

ragel requirements is quite a bit of additional set up for windows users. i did go through the trouble since i will be adding more ops, but i wouldn't want to discourage other windows based users who want to try their hand at hacking teletype firmware.

**Comment by samdoshi** [comment]
Couple of points...

Everyone needs `ragel` installed. Though that can be avoided by added the generated `.c` files to the repo. We would need to adjust the merge strategy via `.gitattributes` to choose the newer version.

Ragel is easily obtained on OSX and Linux.

`op_enums.h` requires Python 3.6 which can be a bit problematic on Linux, though I imagine this will become less so (I think it also predates the ragel stuff, but I can remember when I did what now). That file merges really well, and is actually quite easy to edit by hand if you need to. (FYI, it depends on `op.c` not `match_tokens.rl`.)

Travis CI definitely supports Ragel, not so sure about Python 3.6. I'm going to try adding PDF generation to the CI at some point, I guess I'll find out then.

Docs are not a requirement for contributions either, if I've ever given that impression I apologies.

I'm ambivalent about always generating `op_enums.h`, probably leaning slightly towards it as it's a pain to remember to run the python script. If it is done, I think it should be done as part of a larger Makefile shake up as there is a lot of duplication between the 3 targets (`module`, `tests` and `simulator`).

I'm not super keen on making changes to the benefit of a single user's fork though, I think that makes work for everyone else having to keep it maintained. Any changes need to be framed in terms of what's best for the mainline version. @burnsauce you should find that `git` branches and the `merge`, `rebase`, and `cherry-pick` commands make it very easy for you to maintain your own custom version.

(Also surely the easiest way to nuke the I2C stuff, would be to leave the OPs, but swap out the implementations of `tele_ii_tx` and `tele_ii_rx`?)

Anyway I'm going to close this PR as replacements have been opened up on `monome/teletype`, Probably best to start a thread on lines if you want to continue this discussion in more depth so that the other developers can see it too.

**Comment by scanner-darkly** [comment]
`Everyone needs ragel installed`
 ¯\_(ツ)_/¯

**Comment by samdoshi** [comment]
Actually one more point, the python code to generate `op_enums.h` is not very clever anyway, it won't understand any C macros (it just works using a regexp).

**Pull request closed without merging**
