### PR TITLE
first pass on documentation for TELEX modules

### PR DESCRIPTION
**Pull request by bpcmusic**
Please find the documentation for the TXo and TXi in this pull request. Includes all operators with short descriptions and selected long descriptions for the more complex, TELEX-exclusive operators.

### CODE REVIEW

**Comment by bpcmusic** [comment]
Hey Sam - I've pushed the changes and additional documentation for my new OPs; actual OPs themselves are in their own pull request. Let me know if you need anything else ... and feel free to squash this stuff. Someday, I'll figure out how to do it myself...sorry.

**Comment by samdoshi** [comment]
I had to add a few tweaks so I did it locally and squashed it.

**Comment by bpcmusic** [comment]
What did I goof up? :( Sorry.

**Comment by samdoshi** [comment]
More me than you. I need a blank line at the bottom of each markdown file otherwise it borks. Plus I needed to update `docs.py` so that it was looking for the correct files.

The only mistake you'd made was using `'''` instead of three backticks in the example in `TO.OSC.CTR`. (Cool addition btw)

**Pull request closed without merging**
