### PR TITLE
TELEX aliases and various TELEX init ops

### PR DESCRIPTION
**Pull request by bpcmusic**
From the changelog:

- **NEW**: TELEX Aliases: `TO.TR.P` for `TO.TR.PULSE` (plus all sub-commands) and `TI.PRM` for `TI.PARAM` (plus all sub-commands)
- **NEW**: TELEX initialization commands: `TO.TR.INIT n`, `TO.CV.INIT n`, `TO.INIT x`, `TI.PARAM.INIT n`, `TI.IN.INIT n`, and `TI.INIT x`

Made slight tweak in the readme.md to specify python3 and move the order so that the generator is after the mention of the file it generates from ;)

### CODE REVIEW

**Comment by samdoshi** [comment]
Yeah the travis tests are broken because I'm waiting for https://github.com/monome/libavr32/pull/26 to be merged.

However... `make test` in the `tests` directory is failing if run locally.

I think the following

```c
// TXo Ailiases
const tele_op_t op_TO_TR_P            = MAKE_ALIAS_OP(TO.TR.P           , op_TO_TR_PULSE_get        , NULL, 1, true);
const tele_op_t op_TO_TR_P_DIV        = MAKE_ALIAS_OP(TO.TR.P.DIV       , op_TO_TR_PULSE_DIV_get    , NULL, 2, true);
```

needs to be changed to: 

```c
// TXo Ailiases
const tele_op_t op_TO_TR_P            = MAKE_ALIAS_OP(TO.TR.P           , op_TO_TR_PULSE_get        , NULL, 1, false);
const tele_op_t op_TO_TR_P_DIV        = MAKE_ALIAS_OP(TO.TR.P.DIV       , op_TO_TR_PULSE_DIV_get    , NULL, 2, false);
```

(last argument has changed from `true` to `false`)

I can make the change if you want. Or you can make the change and rewrite history... (or not if that is easier)

```
git add src/ops/telex.c
git commit --amend
git push -f
```

**Comment by bpcmusic** [comment]
Oops; I had run the tests but must have buggered something before submitting. Apologies to waste your time. Got a little lost in git nonsense trying to upload the changes - but think I got it.

**Comment by samdoshi** [comment]
No worries at all. I'll most likely use the 'squash and merge' option which will handily turn your commits into a single one.

**Comment by samdoshi** [comment]
I've squashed and merged the PR.

In case you're not quite sure what that means, don't do anymore work on the `telex_aliases` branch.

**Pull request merged**
